In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [2]:
data = pd.read_csv('C:/Users/OFFICE/Desktop/bOOK/data science/data analysis with python/iris.csv')

In [3]:
data.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [4]:
headers=['petal_length', 'petal_width', 'sepal_length', 'sepal_width','species']
data.columns = headers
data.columns

Index(['petal_length', 'petal_width', 'sepal_length', 'sepal_width',
       'species'],
      dtype='object')

In [5]:
data

     petal_length  petal_width  sepal_length  sepal_width         species
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
5             4.6          3.4           1.4          0.3     Iris-setosa
6             5.0          3.4           1.5          0.2     Iris-setosa
7             4.4          2.9           1.4          0.2     Iris-setosa
8             4.9          3.1           1.5          0.1     Iris-setosa
9             5.4          3.7           1.5          0.2     Iris-setosa
10            4.8          3.4           1.6          0.2     Iris-setosa
11            4.8          3.0           1.4          0.1     Iris-setosa
12            4.3          3.0           1.1          0.1     Iris-setosa
13            5.8          4.0           1.2          0.2     Iris-setosa
14            5.7          4.4           1.5          0.4     Iris-setosa
15            5.4          3.9           1.3          0.4     Iris-setosa
16            5.1          3.5           1.4          0.3     Iris-setosa
17            5.7          3.8           1.7          0.3     Iris-setosa
18            5.1          3.8           1.5          0.3     Iris-setosa
19            5.4          3.4           1.7          0.2     Iris-setosa
20            5.1          3.7           1.5          0.4     Iris-setosa
21            4.6          3.6           1.0          0.2     Iris-setosa
22            5.1          3.3           1.7          0.5     Iris-setosa
23            4.8          3.4           1.9          0.2     Iris-setosa
24            5.0          3.0           1.6          0.2     Iris-setosa
25            5.0          3.4           1.6          0.4     Iris-setosa
26            5.2          3.5           1.5          0.2     Iris-setosa
27            5.2          3.4           1.4          0.2     Iris-setosa
28            4.7          3.2           1.6          0.2     Iris-setosa
29            4.8          3.1           1.6          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
119           6.9          3.2           5.7          2.3  Iris-virginica
120           5.6          2.8           4.9          2.0  Iris-virginica
121           7.7          2.8           6.7          2.0  Iris-virginica
122           6.3          2.7           4.9          1.8  Iris-virginica
123           6.7          3.3           5.7          2.1  Iris-virginica
124           7.2          3.2           6.0          1.8  Iris-virginica
125           6.2          2.8           4.8          1.8  Iris-virginica
126           6.1          3.0           4.9          1.8  Iris-virginica
127           6.4          2.8           5.6          2.1  Iris-virginica
128           7.2          3.0           5.8          1.6  Iris-virginica
129           7.4          2.8           6.1          1.9  Iris-virginica
130           7.9          3.8           6.4          2.0  Iris-virginica
131           6.4          2.8           5.6          2.2  Iris-virginica
132           6.3          2.8           5.1          1.5  Iris-virginica
133           6.1          2.6           5.6          1.4  Iris-virginica
134           7.7          3.0           6.1          2.3  Iris-virginica
135           6.3          3.4           5.6          2.4  Iris-virginica
136           6.4          3.1           5.5          1.8  Iris-virginica
137           6.0          3.0           4.8          1.8  Iris-virginica
138           6.9          3.1           5.4          2.1  Iris-virginica
139           6.7          3.1           5.6          2.4  Iris-virginica
140           6.9          3.1           5.1          2.3  Iris-virginica
141           5.8          2.7           5.1          1.9  Iris-virginica
142           6.8          3.2           5.9          2.3  Iris-virginica
143           6.7          3.3           5.7          2.5  Iris-virginica
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

In [6]:
data[data.isnull().any(axis=1)]

Empty DataFrame
Columns: [petal_length, petal_width, sepal_length, sepal_width, species]
Index: []

In [7]:
before_rows= data.shape[0]
print(before_rows)

149

In [8]:
data=data.dropna()

In [9]:
after_rows= data.shape[0]
print(after_rows)

149

## convert to classification task

In [12]:
clean_data = data.copy()
clean_data['high_petal_length'] = (clean_data['petal_length']>5)*1
clean_data['high_petal_length']

0      0
1      0
2      0
3      0
4      1
5      0
6      0
7      0
8      0
9      1
10     0
11     0
12     0
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     0
22     1
23     0
24     0
25     0
26     1
27     1
28     0
29     0
      ..
119    1
120    1
121    1
122    1
123    1
124    1
125    1
126    1
127    1
128    1
129    1
130    1
131    1
132    1
133    1
134    1
135    1
136    1
137    1
138    1
139    1
140    1
141    1
142    1
143    1
144    1
145    1
146    1
147    1
148    1
Name: high_petal_length, Length: 149, dtype: int32

In [23]:
yk = clean_data[['high_petal_length']].copy()
yk

     high_petal_length
0                    0
1                    0
2                    0
3                    0
4                    1
5                    0
6                    0
7                    0
8                    0
9                    1
10                   0
11                   0
12                   0
13                   1
14                   1
15                   1
16                   1
17                   1
18                   1
19                   1
20                   1
21                   0
22                   1
23                   0
24                   0
25                   0
26                   1
27                   1
28                   0
29                   0
..                 ...
119                  1
120                  1
121                  1
122                  1
123                  1
124                  1
125                  1
126                  1
127                  1
128                  1
129                  1
130                  1
131                  1
132                  1
133                  1
134                  1
135                  1
136                  1
137                  1
138                  1
139                  1
140                  1
141                  1
142                  1
143                  1
144                  1
145                  1
146                  1
147                  1
148                  1

[149 rows x 1 columns]

In [17]:
clean_data['petal_length'].head()

0    4.9
1    4.7
2    4.6
3    5.0
4    5.4
Name: petal_length, dtype: float64

In [24]:
yk.head()

   high_petal_length
0                  0
1                  0
2                  0
3                  0
4                  1

using petal and sepal lengths and wdth to prdict the species.

In [19]:
lengths=['petal_length','petal_width','sepal_length','sepal_width']

In [22]:
x = clean_data[lengths].copy() #if complicated values use deep copy i.e in copy(deep=True).

In [21]:
x.columns

Index(['petal_length', 'petal_width', 'sepal_length', 'sepal_width'], dtype='object')

In [25]:
x.head()

   petal_length  petal_width  sepal_length  sepal_width
0           4.9          3.0           1.4          0.2
1           4.7          3.2           1.3          0.2
2           4.6          3.1           1.5          0.2
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4

In [27]:
y=clean_data['species']
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: object

## perform test and train split

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.33, random_state=324)

In [41]:
#print(x_train)
#print(x_test)
#print(y_train)
#print(y_test)
#x_train.head()
#y_train.describe()

### fit on train set

In [35]:
species_classifier = DecisionTreeClassifier(max_leaf_nodes=5,random_state=0)
species_classifier.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=5, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best')

In [36]:
type(species_classifier)

sklearn.tree.tree.DecisionTreeClassifier

### predict on test data

In [37]:
predictions = species_classifier.predict(x_test)

In [38]:
predictions[:10]

array(['Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa'], dtype=object)

In [39]:
y_test['species'][:10]

KeyError: 'species'

### measure accuracy of the classifier

In [42]:
accuracy_score(y_true=y_test, y_pred=predictions)

0.94